### PR TITLE
Fixing issue performance of group and owner file attribute cache which was introduced in 2.6.1

### PR DESCRIPTION
**Pull request by Classe**
A fix for https://github.com/codehaus-plexus/plexus-io/issues/16

### CODE REVIEW

**Comment by Classe** [comment]
Is this fix okay from your point of view? Asking if I should attend fixing the rest of the builds

**Comment by Classe** [comment]
@plamentotev @krosenvold what do you think about this?

**Comment by plamentotev** [comment]
Hi,
Thank you for the contribution. Really appreciate it that you took your time to investigate and share back with the community. Those kind of problems are quite hard to spot and find especially when they  manifest only on certain configurations. 

I can take a look latter this week, but in general the changes look ok.

**Comment by michael-o** [comment]
The question is: why does `unix:*` incur so much overhead? We are likely fixing the symptom, but not the real cause.

**Comment by Classe** [comment]
I would say that fetching group name and owner name can be lookup heavy on some systems with some security related to mapping group and owner name to gid/uid. This causes the issue together with the 2.6.1 that unintentionally disabled this naming lookup caching.

**Comment by olamy** [comment]
LGTM maybe you can write some jmh tests to compare. I'm happy to run them on a beefy machine.

**Comment by Classe** [comment]
Just need to figure out how to squash the commits and push it to same pull request

**Comment by Classe** [comment]
Now I think I got it right :) thanks for the patience.

**Comment by plamentotev** [comment]
Looks great. Thanks again for your contribution.

**Pull request closed without merging**
